name: Gasandelec-Brighton
favicon: null
layout_spectrum: 0.7771763922646642
typography_spectrum: 0.7473600876983255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.843635251512751
  lightness: 0.8171826153993607
  saturation: 0.7925820674281567
  rhythmicContrast: 0.298367504728958
purpose: []
